cache:
  directories:
    - node_modules
install:
  - "npm install"
language: node_js
node_js:
  - node
script:
  - npm run test
services:
  - mongodb
after_success:
  - npm run coveralls
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  global:
    - CC_TEST_REPORTER_ID=444ea9b6e3ebff47dd1d9cf2e9169de02105e34c09d585349148783436868d37
